export const homeObjOne = {
    id: 'about',
    lightBg : true ,
    lightText : true ,
    lightTextDesc: false ,
    topLine: 'Technological Awareness Month',
    headline : 'Welcome to TAM' ,
    description : 'TAM stands for technology awareness month, where we conduct events on generating awareness amongst students about the latest practical technologies in the industry of engineering. We focus on bringing light to the topics that are usually hind-sighted by the students of engineering.',
    desc: 'Creating a better knowledge-base and testing their wits on various levels, TAM stands to be a knowledge-parting legacy from years! We are more than proud to introduce version 8 of TAM for the year 2021-22. Come and join us to be a part of the biggest intelligence-rave of St. Martin’s Engineering College.',
    buttonLabel : 'Browse Events' ,
    imgStart : true ,
    img : require('../../images/Crew.png') ,
    alt : 'TAM',
    dark : false ,
    primary : false , 
    darkText : true ,
    to : 'events' ,
    linkS : true , 
    linkR : false, 
} ;

export const homeObjTwo = {
    id: 'events',
    lightBg : false ,
    lightText : false ,
    lightTextDesc: true ,
    topLine: 'Events',
    headline : 'Events for Everyone ' ,
    description : 'What is learning with no fun? We conduct workshops on various subjects like ARDUINO, CYBER SECURITY etc, for students to learn and also practice alongside with industry-based subject matter experts! Where you can learn how to work these subjects on an industry-level. Join the workshops by registering below to be the jack of all trades!!',
    buttonLabel : 'Details' ,
    imgStart : false ,
    img : require('../../images/events.png') ,
    alt : 'TAM',
    dark : true ,
    primary : true , 
    darkText : false ,
    to: 'about',
    linkS : false , 
    linkR : false,
} ;

export const homeObjThree = {
    id: 'team',
    lightBg : false ,
    lightText : false ,
    lightTextDesc: true ,
    topLine: 'Team',
    headline : 'Meet The Crew' ,
    description : 'Something related to team',
    buttonLabel : 'Know us Better' ,
    imgStart : true ,
    img : require('../../images/team.png') ,
    alt : 'TAM',
    dark : true ,
    primary : true , 
    darkText : false ,
    to : '/CrewPage',
    linkS : false , 
    linkR : true,
} ;

export const homeObjFour  = {
    id: 'help',
    lightBg : false ,
    lightText : false ,
    lightTextDesc: true ,                        
    topLine: 'Help',
    headline : 'Stuck? How Can we Help ' ,
    description : 'Some FAQs to help you',
    buttonLabel : 'Contact Us' ,
    imgStart : false ,
    img : require('../../images/tam4.png') ,
    alt : 'TAM',
    dark : true ,
    primary : true , 
    darkText : false ,
    to : '/goToGoogle',
    linkS : false , 
    linkR : false,
    linkC : true,
} ;

export const homeObjFive  = {
    id: 'quiz',
    lightBg : false ,
    lightText : false ,
    lightTextDesc: true ,                       
    topLine: 'QUIZZES',
    headline : 'Give your brain some exercise ' ,
    description : 'Quizzes are conducted to bring out the competitive side in you. Go on, grab a friend or a fellow classmate to challenge the knowledge which you have gained over the years. The quizzes mention below have two rounds each.',
    buttonLabel : 'View Quizzes' ,
    imgStart : false ,
    img : require('../../images/quiz.png') ,
    alt : 'TAM',
    dark : true ,
    primary : true , 
    darkText : false ,
    to : 'about',
    linkS : false , 
    linkR : false,
} ;

export const tech = {
    id: 'tech',
    lightBg : false ,
    lightText : false ,
    lightTextDesc: true ,
    topLine: 'Technical Department',
    headline : 'TECHIES' ,
    description : 'Role Of Technical Department',
    buttonLabel : 'Get Started' ,
    imgStart : true ,
    img : require('../../images/tam.png') ,
    alt : 'TAM',
    dark : true ,
    primary : true , 
    darkText : false ,
    to : 'events' ,
    linkS : false , 
    linkR : false, 
} ;

export const marketing = {
    id: 'market',
    lightBg : false ,
    lightText : false ,
    lightTextDesc: true ,
    topLine: 'Marketing Department',
    headline : 'MARKETEERS' ,
    description : 'Role Of Marketing Department',
    buttonLabel : 'Get Started' ,
    imgStart : true ,
    img : require('../../images/tam.png') ,
    alt : 'TAM',
    dark : true ,
    primary : true , 
    darkText : false ,
    to : 'events' ,
    linkS : false , 
    linkR : false, 
} ;

export const events = {
    id: 'evemts',
    lightBg : false ,
    lightText : false ,
    lightTextDesc: true ,
    topLine: 'Events Department',
    headline : 'EVENTERS' ,
    description : 'Role Of Event Department',
    buttonLabel : 'Get Started' ,
    imgStart : true ,
    img : require('../../images/tam.png') ,
    alt : 'TAM',
    dark : true ,
    primary : true , 
    darkText : false ,
    to : 'events' ,
    linkS : false , 
    linkR : false, 
} ;

