export const homeObjOne = {
    id: 'about',
    lightBg : true ,
    lightText : true ,
    lightTextDesc: false ,
    topLine: 'Technological Awareness Month',
    headline : 'Welcome to TAM' ,
    description : 'Something related to tam',
    buttonLabel : 'Browse Events' ,
    imgStart : true ,
    img : require('../../images/Crew.jpeg') ,
    alt : 'TAM',
    dark : false ,
    primary : false , 
    darkText : true ,
    to : 'events' ,
    linkS : true , 
    linkR : false, 
} ;

export const homeObjTwo = {
    id: 'events',
    lightBg : false ,
    lightText : false ,
    lightTextDesc: true ,
    topLine: 'Events',
    headline : 'Events for Everyone ' ,
    description : 'Something related to tam',
    buttonLabel : 'Details' ,
    imgStart : false ,
    img : require('../../images/events.png') ,
    alt : 'TAM',
    dark : true ,
    primary : true , 
    darkText : false ,
    to: 'about',
    linkS : false , 
    linkR : false,
} ;

export const homeObjThree = {
    id: 'team',
    lightBg : false ,
    lightText : false ,
    lightTextDesc: true ,
    topLine: 'Team',
    headline : 'Meet The Crew' ,
    description : 'Something related to team',
    buttonLabel : 'Know us Better' ,
    imgStart : true ,
    img : require('../../images/team.JPG') ,
    alt : 'TAM',
    dark : true ,
    primary : true , 
    darkText : false ,
    to : '/CrewPage',
    linkS : false , 
    linkR : true,
} ;

export const homeObjFour  = {
    id: 'help',
    lightBg : false ,
    lightText : false ,
    lightTextDesc: true ,                        
    topLine: 'Help',
    headline : 'Stuck? How Can we Help ' ,
    description : 'Some FAQs to help you',
    buttonLabel : 'Contact Us' ,
    imgStart : false ,
    img : require('../../images/tam4.png') ,
    alt : 'TAM',
    dark : true ,
    primary : true , 
    darkText : false ,
    to : 'about',
    linkS : true , 
    linkR : false,
} ;

export const homeObjFive  = {
    id: 'quiz',
    lightBg : false ,
    lightText : false ,
    lightTextDesc: true ,                       
    topLine: 'QUIZZES',
    headline : 'Give your brain some exercise ' ,
    description : 'Something about quizzes',
    buttonLabel : 'View Quizzes' ,
    imgStart : false ,
    img : require('../../images/quiz.png') ,
    alt : 'TAM',
    dark : true ,
    primary : true , 
    darkText : false ,
    to : 'about',
    linkS : false , 
    linkR : false,
} ;

export const tech = {
    id: 'tech',
    lightBg : false ,
    lightText : false ,
    lightTextDesc: true ,
    topLine: 'TECHNICAL DEPARTMENT',
    headline : 'TECHIES' ,
    description : 'ROLE OF TECHNICAL DEPARTMENT',
    buttonLabel : 'Get Started' ,
    imgStart : true ,
    img : require('../../images/tam.png') ,
    alt : 'TAM',
    dark : true ,
    primary : true , 
    darkText : false ,
    to : 'events' ,
    linkS : false , 
    linkR : false, 
} ;

export const marketing = {
    id: 'market',
    lightBg : false ,
    lightText : false ,
    lightTextDesc: true ,
    topLine: 'Marketing DEPARTMENT',
    headline : 'MARKETEERS' ,
    description : 'ROLE OF Marketing DEPARTMENT',
    buttonLabel : 'Get Started' ,
    imgStart : true ,
    img : require('../../images/tam.png') ,
    alt : 'TAM',
    dark : true ,
    primary : true , 
    darkText : false ,
    to : 'events' ,
    linkS : false , 
    linkR : false, 
} ;

